pipeline:
  build:
    image: ${RUST_VERSION}
    commands:
      - rustup show
      - cargo build
      - cargo test

matrix:
  RUST_VERSION:
    - rust:1.26
    - rust:latest
    - rustlang/rust:nightly
