pipeline:
  build:
    image: ${RUST_VERSION}
    secrets: [ codecov_token ]
    commands:
      - rustup show
      - cargo build
      - cargo test
      - |
        if [ "${RUST_VERSION}" = "rustlang/rust:nightly" ]; then
          apt-get update
          apt-get install -y --no-install-recommends lcov llvm
          ./util/run-cov.sh
          curl -s https://codecov.io/bash > .codecov
          chmod +x .codecov
          ./.codecov -f final.info -t $CODECOV_TOKEN
        fi

matrix:
  RUST_VERSION:
    - rust:1.26
    - rust:latest
    - rustlang/rust:nightly
