[package]
name = "mesatools"
version = "0.1.0"
authors = ["Alex Lyon <alexlyon@baidu.com>"]
description = "A collection of utilities important to basic system functionality"
build = "build.rs"

[features]
yes = []

posix = ["yes"]

default-features = ["posix"]

[dependencies]
clap = "2.31.2"
failure = "0.1.1"
libc = "0.2.40"
platform-info = { git = "https://github.com/uutils/platform-info" }
tar = "0.4.15"
globset = "0.4.0"
quick-error = "1.2.1"
nix = "0.10.0"

[build-dependencies]
rustc_version = "0.2.2"

[profile.release]
panic = "abort"
