[package]
name = "mesabox"
version = "0.1.0"
authors = ["Alex Lyon <alexlyon@baidu.com>"]
description = "A collection of utilities important to basic system functionality"
build = "build.rs"

[features]
arch = []
base32 = []
base64 = []
yes = []
gnu = [
    "arch",
    "base32",
    "base64",
    "yes"
]

getty = []
loginutils = [
    "getty"
]

# XXX: temporary until renaming dependencies is supported
tar_util = []
lsb = [
    "tar_util"
]

ping = []
networking = [
    "ping"
]

cat = []
chmod = []
head = []
init = []
sleep = []
posix = [
    "cat",
    "chmod",
    "head",
    "init",
    "sleep"
]

default = ["gnu", "loginutils", "lsb", "networking", "posix"]

[dependencies]
clap = "2.31.2"
failure = "0.1.1"
failure_derive = "0.1.1"
libc = "0.2.40"
platform-info = { git = "https://github.com/uutils/platform-info" }
uucore = { git = "https://github.com/uutils/coreutils", features = ["encoding", "fs", "mode", "parse_time"] }
tar = "0.4.15"
globset = "0.4.0"
nix = "0.10.0"
chrono = "0.4.2"
crossbeam = "0.3.2"
pnet = "0.21.0"
byteorder = "1.2.3"
trust-dns-resolver = "0.9.0"
mio = "0.6.14"
socket2 = "0.3.5"
walkdir = "2.1.4"
fnv = "1.0.6"
regex = "1.0.0"

[dev-dependencies]
tempfile = "3.0.2"
libc = "0.2.40"
lazy_static = "1.0.1"

[profile.release]
lto = true
panic = "abort"

[[test]]
name = "tests"
